Models/ErrorViewModel.cs
namespace MvcIntroViews.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/CalculadoraController.cs
using Microsoft.AspNetCore.Mvc;

namespace MvcIntroViews.Controllers;

public class CalculadoraController : Controller
{
    public IActionResult Index()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Resultado(double num1, double num2, string operacao)
    {
        ViewBag.Num1 = num1;
        ViewBag.Num2 = num2;
        ViewBag.Operacao = operacao;

        switch (operacao)
        {
            case "Soma":
                ViewBag.Resultado = num1 + num2;
                ViewBag.Sinal = "+";
                break;
            case "Subtração":
                ViewBag.Resultado = num1 - num2;
                ViewBag.Sinal = "-";
                break;
            case "Multiplicação":
                ViewBag.Resultado = num1 * num2;
                ViewBag.Sinal = "*";
                break;
            case "Divisão":
                ViewBag.Resultado = num1 / num2;
                ViewBag.Sinal = "/";
                break;
        }
        return View();
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MvcIntroViews.Models;

namespace MvcIntroViews.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/OperacoesController.cs
using Microsoft.AspNetCore.Mvc;

namespace MvcIntroViews.Controllers;

public class OperacoesController : Controller
{
    public IActionResult Somar()
    {
        return View();
    }
     
     public IActionResult ResultadoSoma(double n1, double n2)
     {
        ViewBag.N1 = n1;
        ViewBag.N2 = n2;
        ViewBag.Resultado = n1 + n2;
        return View();

     }
      public IActionResult Subtracao() => View();

    public IActionResult ResultadoSubtracao(double n1, double n2)
    {
        ViewBag.N1 = n1;
        ViewBag.N2 = n2;
        ViewBag.Resultado = n1 - n2;
        return View();
    }

    public IActionResult Multiplicacao() => View();

    public IActionResult ResultadoMultiplicacao(double n1, double n2)
    {
        ViewBag.N1 = n1;
        ViewBag.N2 = n2;
        ViewBag.Resultado = n1 * n2;
        return View();
    }

    public IActionResult Divisao() => View();

    public IActionResult ResultadoDivisao(double n1, double n2)
    {
        ViewBag.N1 = n1;
        ViewBag.N2 = n2;
        ViewBag.Resultado = n1 / n2;
        return View();
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Operacoes/Divisao.cshtml
@{
    ViewData["Title"] = "Divisão";
}

<div>
    <h3>Operação Dividir</h3>
    <p>Acesse o formulário a seguir para dividir os dois números a seguir</p>

    <form asp-controller="Operacoes" asp-action="ResultadoDivisao" method="post">
        <label for="n1">Número 1</label>
        <input type="text" name="n1" id="n1">

        <label for="n2">Número 2</label>
        <input type="text" name="n2" id="n2">

        <input type="submit" value="Dividir">
    </form>
</div>

Views/Operacoes/Multiplicacao.cshtml
@{
    ViewData["Title"] = "Multiplicação";
}

<div>
    <h3>Operação Multiplicar</h3>
    <p>Acesse o formulário a seguir para multiplicar os dois números inseridos</p>

    <form asp-controller="Operacoes" asp-action="ResultadoMultiplicacao" method="post">
        <label for="n1">Número 1</label>
        <input type="text" name="n1" id="n1">

        <label for="n2">Número 2</label>
        <input type="text" name="n2" id="n2">

        <input type="submit" value="Multiplicar">
    </form>
</div>

Views/Operacoes/ResultadoDivisao.cshtml
@{
    ViewData["Title"] = "Resultado Divisao";
}

<h1>Resultado divisão</h1>
<p>O resultado da divisão de @ViewBag.N1 / @ViewBag.N2 é igual a @ViewBag.Resultado</p>

Views/Operacoes/ResultadoMultiplicacao.cshtml
@{
    ViewData["Title"] = "Resultado Multiplicação";
}

<h1>Resultado Multiplicação</h1>
<p>O resultado da multiplicação de @ViewBag.N1 x @ViewBag.N2 é igual a @ViewBag.Resultado</p>

Views/Operacoes/ResultadoSoma.cshtml
@{
    ViewData["Title"] = "Resultado Soma";
}
<h1>Resultado Soma</h1>
<p>O resultado da soma de @ViewBag.N1 + @ViewBag.N2 é igual  a @ViewBag.Resultado</p>

Views/Operacoes/ResultadoSubtracao.cshtml
@{
    ViewData["Title"] = "Resultado Subtração";
}

<h1>Resultado Subtração</h1>
<p>O resultado da subtração de @ViewBag.N1 - @ViewBag.N2 é igual a @ViewBag.Resultado</p>
Footer
© 2022 GitHub, Inc.
Footer navigation
Terms
Privacy
Security
Status

Views/Operacoes/Somar.cshtml
@{
    ViewData["Title"] = "Somar";
}
<h1>Calculadora Soma</h1>
<form action="/Operacoes/ResultadoSoma" method="post">
<label for="n1"> Numero 1</label>
<input type="text" name= "n1" id="n1">

<label for="n2"> Numero 2</label>
<input type="text" name= "n2" id="n2">

<input type="submit" value="Somar">
</form>

Views/Operacoes/Subtracao.cshtml
@{
    ViewData["Title"] = "Subtração";
}

<div>
    <h3>Operação Subtrair</h3>
    <p>Acesse o formulário a seguir para subtrair os dois números inseridos</p>

    <form asp-controller="Operacoes" asp-action="ResultadoSubtracao" method="post">
        <label for="n1">Número 1</label>
        <input type="text" name="n1" id="n1">

        <label for="n2">Número 2</label>
        <input type="text" name="n2" id="n2">

        <input type="submit" value="Subtrair">
    </form>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcIntroViews</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcIntroViews.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcIntroViews</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Operacoes" asp-action="Soma">&plus; Soma</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Operacoes" asp-action="Subtracao">&minus; Subtração</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Operacoes" asp-action="Multiplicacao">&times; Multiplicação</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Operacoes" asp-action="Divisao">&divide; Divisão</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calculadora" asp-action="Index">Calculadora</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MvcIntroViews - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>